import React from "react";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";
import { getTranslations } from "next-intl/server";
import { Link } from "../../i18n/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const t = await getTranslations("HomePage");
  return (
    <html lang={locale}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Hello International!</title>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css"
        />
      </head>
      <body
        style={{
          margin: "3rem",
        }}
      >
        <NextIntlClientProvider>
          <header className="navbar">
            <Link href="/">{t("home")}</Link>
            {" | "}
            <Link href="/about">{t("about")}</Link>
            {" | "}
            <Link href="/posts">{t("posts")}</Link>
          </header>
          <main>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
